### ISSUE TITLE
Any chance you could do a tweetdeck version?

### ISSUE THREAD

**Issue by xircon** [theoosborn/firefox-twitter-sidebar#1]
I tried hacking the url, but no text displays in the tweets.  I prefer tweetdeck because you can filter out all the promotional tweets.

Cheers

Steve

**Comment by theoosborn** [comment]
Thanks for the suggestion, I'll see if I can add it to settings of this extension. If not, I'll create another version of the add-on for Tweetdeck.

**Comment by theoosborn** [comment]
This is live in the latest release v1.5.2 - thanks for your patience!

**Comment by xircon** [comment]
Thanks! All working well so far.
