### ISSUE TITLE
Pinned lists pane - thumbnails slide only one direction. 

### ISSUE THREAD

**Issue by scrutinizer11** [theoosborn/firefox-twitter-sidebar#5]
if you pin lists and the view can't display all of them (it's 3 or 4 by default and the number of the pinned lists exceeds the default) then you can go to the last thumbnail by hitting the right arrow but cannot do the reverse action – get back to the previous thumbnails. The reason - only the right arrow is active but the left one is missing. Fix this, please. Your extension is awesome.

Firefox on macOS.

**Comment by theoosborn** [comment]
Unfortunately this would be an issue with Twitter rather than the extension - all my extension does is display the webpage in the sidebar.

However, I have just tested it and it seems that while the left arrow is still missing, you can use the keyboard arrows to navigate the pinned lists.
